export { createInstance } from "./api-instance";
export type { IMovie } from "./types";
export type { IFetchMoviePopular } from "./types";
export type { IFetchMoviePopularParams } from "./types";
export type { BodyType } from "./api-instance";
export type { IFetchMovieDetails } from "./types";
export type { IMovieDetails } from "./types";
export type { IGenre } from "./types";
export type { IFetchMovieDetailsParams } from "./types";
export type { IFetchMovieSimilar } from "./types";
export type { IFetchMovieSimilarParams } from "./types";
export type { IFetchMovieTopRated } from "./types";
export type { IFetchMovieTopRatedParams } from "./types";
